---
engines:
  fixme:
    enabled: true
  gnu-complexity:
    enabled: true
    config:
      threshold: 100
ratings:
  paths: []
exclude_paths:
  include/SDL2/
  bin/
  data/
  dep/
  screenshots/
  latex/
  img/
  html/
  font/
  audio/
