var hierarchy =
[
    [ "Camera", "class_camera.html", null ],
    [ "Circle", "class_circle.html", null ],
    [ "CompCollider::Coll", "struct_comp_collider_1_1_coll.html", null ],
    [ "Component", "class_component.html", [
      [ "CompAI", "class_comp_a_i.html", null ],
      [ "CompAnim", "class_comp_anim.html", null ],
      [ "CompAnimControl", "class_comp_anim_control.html", null ],
      [ "CompCollider", "class_comp_collider.html", null ],
      [ "CompGravity", "class_comp_gravity.html", null ],
      [ "CompHP", "class_comp_h_p.html", null ],
      [ "CompInputControl", "class_comp_input_control.html", null ],
      [ "CompMemory", "class_comp_memory.html", null ],
      [ "CompMovement", "class_comp_movement.html", null ],
      [ "CompStaticRender", "class_comp_static_render.html", null ],
      [ "CompText", "class_comp_text.html", null ],
      [ "CompTimer", "class_comp_timer.html", null ]
    ] ],
    [ "ConvexPolygon", "class_convex_polygon.html", null ],
    [ "exception", null, [
      [ "GameException", "class_game_exception.html", null ]
    ] ],
    [ "Game", "class_game.html", null ],
    [ "GameObject", "class_game_object.html", null ],
    [ "GUI_Element", "class_g_u_i___element.html", [
      [ "GUI_Array", "class_g_u_i___array.html", [
        [ "GUI_HBar", "class_g_u_i___h_bar.html", null ],
        [ "GUI_VBar", "class_g_u_i___v_bar.html", null ]
      ] ],
      [ "GUI_Button", "class_g_u_i___button.html", [
        [ "GUI_CheckButton", "class_g_u_i___check_button.html", null ],
        [ "GUI_IconButton", "class_g_u_i___icon_button.html", null ],
        [ "GUI_InputBox", "class_g_u_i___input_box.html", [
          [ "GUI_IntBox", "class_g_u_i___int_box.html", null ],
          [ "GUI_StringBox", "class_g_u_i___string_box.html", null ]
        ] ],
        [ "GUI_TextButton", "class_g_u_i___text_button.html", null ]
      ] ],
      [ "GUI_Label", "class_g_u_i___label.html", null ],
      [ "GUI_Window", "class_g_u_i___window.html", null ]
    ] ],
    [ "GUIManager", "class_g_u_i_manager.html", null ],
    [ "InputManager", "class_input_manager.html", null ],
    [ "Level", "class_level.html", null ],
    [ "Mix_Chunk", "struct_mix___chunk.html", null ],
    [ "Music", "class_music.html", null ],
    [ "Rect", "class_rect.html", null ],
    [ "Resources", "class_resources.html", null ],
    [ "SDL_AssertData", "struct_s_d_l___assert_data.html", null ],
    [ "SDL_atomic_t", "struct_s_d_l__atomic__t.html", null ],
    [ "SDL_AudioCVT", "struct_s_d_l___audio_c_v_t.html", null ],
    [ "SDL_AudioDeviceEvent", "struct_s_d_l___audio_device_event.html", null ],
    [ "SDL_AudioSpec", "struct_s_d_l___audio_spec.html", null ],
    [ "SDL_Color", "struct_s_d_l___color.html", null ],
    [ "SDL_CommonEvent", "struct_s_d_l___common_event.html", null ],
    [ "SDL_ControllerAxisEvent", "struct_s_d_l___controller_axis_event.html", null ],
    [ "SDL_ControllerButtonEvent", "struct_s_d_l___controller_button_event.html", null ],
    [ "SDL_ControllerDeviceEvent", "struct_s_d_l___controller_device_event.html", null ],
    [ "SDL_DisplayMode", "struct_s_d_l___display_mode.html", null ],
    [ "SDL_DollarGestureEvent", "struct_s_d_l___dollar_gesture_event.html", null ],
    [ "SDL_DropEvent", "struct_s_d_l___drop_event.html", null ],
    [ "SDL_Event", "union_s_d_l___event.html", null ],
    [ "SDL_Finger", "struct_s_d_l___finger.html", null ],
    [ "SDL_GameControllerButtonBind", "struct_s_d_l___game_controller_button_bind.html", null ],
    [ "SDL_HapticCondition", "struct_s_d_l___haptic_condition.html", null ],
    [ "SDL_HapticConstant", "struct_s_d_l___haptic_constant.html", null ],
    [ "SDL_HapticCustom", "struct_s_d_l___haptic_custom.html", null ],
    [ "SDL_HapticDirection", "struct_s_d_l___haptic_direction.html", null ],
    [ "SDL_HapticEffect", "union_s_d_l___haptic_effect.html", null ],
    [ "SDL_HapticLeftRight", "struct_s_d_l___haptic_left_right.html", null ],
    [ "SDL_HapticPeriodic", "struct_s_d_l___haptic_periodic.html", null ],
    [ "SDL_HapticRamp", "struct_s_d_l___haptic_ramp.html", null ],
    [ "SDL_JoyAxisEvent", "struct_s_d_l___joy_axis_event.html", null ],
    [ "SDL_JoyBallEvent", "struct_s_d_l___joy_ball_event.html", null ],
    [ "SDL_JoyButtonEvent", "struct_s_d_l___joy_button_event.html", null ],
    [ "SDL_JoyDeviceEvent", "struct_s_d_l___joy_device_event.html", null ],
    [ "SDL_JoyHatEvent", "struct_s_d_l___joy_hat_event.html", null ],
    [ "SDL_JoystickGUID", "struct_s_d_l___joystick_g_u_i_d.html", null ],
    [ "SDL_KeyboardEvent", "struct_s_d_l___keyboard_event.html", null ],
    [ "SDL_Keysym", "struct_s_d_l___keysym.html", null ],
    [ "SDL_MessageBoxButtonData", "struct_s_d_l___message_box_button_data.html", null ],
    [ "SDL_MessageBoxColor", "struct_s_d_l___message_box_color.html", null ],
    [ "SDL_MessageBoxColorScheme", "struct_s_d_l___message_box_color_scheme.html", null ],
    [ "SDL_MessageBoxData", "struct_s_d_l___message_box_data.html", null ],
    [ "SDL_MouseButtonEvent", "struct_s_d_l___mouse_button_event.html", null ],
    [ "SDL_MouseMotionEvent", "struct_s_d_l___mouse_motion_event.html", null ],
    [ "SDL_MouseWheelEvent", "struct_s_d_l___mouse_wheel_event.html", null ],
    [ "SDL_MultiGestureEvent", "struct_s_d_l___multi_gesture_event.html", null ],
    [ "SDL_OSEvent", "struct_s_d_l___o_s_event.html", null ],
    [ "SDL_Palette", "struct_s_d_l___palette.html", null ],
    [ "SDL_PixelFormat", "struct_s_d_l___pixel_format.html", null ],
    [ "SDL_Point", "struct_s_d_l___point.html", null ],
    [ "SDL_QuitEvent", "struct_s_d_l___quit_event.html", null ],
    [ "SDL_Rect", "struct_s_d_l___rect.html", null ],
    [ "SDL_RendererInfo", "struct_s_d_l___renderer_info.html", null ],
    [ "SDL_RWops", "struct_s_d_l___r_wops.html", null ],
    [ "SDL_Surface", "struct_s_d_l___surface.html", null ],
    [ "SDL_SysWMEvent", "struct_s_d_l___sys_w_m_event.html", null ],
    [ "SDL_SysWMinfo", "struct_s_d_l___sys_w_minfo.html", null ],
    [ "SDL_SysWMmsg", "struct_s_d_l___sys_w_mmsg.html", null ],
    [ "SDL_TextEditingEvent", "struct_s_d_l___text_editing_event.html", null ],
    [ "SDL_TextInputEvent", "struct_s_d_l___text_input_event.html", null ],
    [ "SDL_TouchFingerEvent", "struct_s_d_l___touch_finger_event.html", null ],
    [ "SDL_UserEvent", "struct_s_d_l___user_event.html", null ],
    [ "SDL_version", "struct_s_d_l__version.html", null ],
    [ "SDL_WindowEvent", "struct_s_d_l___window_event.html", null ],
    [ "SDL_WindowShapeMode", "struct_s_d_l___window_shape_mode.html", null ],
    [ "SDL_WindowShapeParams", "union_s_d_l___window_shape_params.html", null ],
    [ "SDLTest_CommonState", "struct_s_d_l_test___common_state.html", null ],
    [ "SDLTest_Crc32Context", "struct_s_d_l_test___crc32_context.html", null ],
    [ "SDLTest_Md5Context", "struct_s_d_l_test___md5_context.html", null ],
    [ "SDLTest_RandomContext", "struct_s_d_l_test___random_context.html", null ],
    [ "SDLTest_SurfaceImage_s", "struct_s_d_l_test___surface_image__s.html", null ],
    [ "SDLTest_TestCaseReference", "struct_s_d_l_test___test_case_reference.html", null ],
    [ "SDLTest_TestSuiteReference", "struct_s_d_l_test___test_suite_reference.html", null ],
    [ "Settings", "class_settings.html", null ],
    [ "Sound", "class_sound.html", null ],
    [ "Sprite", "class_sprite.html", null ],
    [ "State", "class_state.html", [
      [ "StateEditor", "class_state_editor.html", null ],
      [ "StateStage", "class_state_stage.html", null ],
      [ "StateTitle", "class_state_title.html", null ]
    ] ],
    [ "Text", "class_text.html", null ],
    [ "Text::TextLine", "class_text_1_1_text_line.html", null ],
    [ "TileMap", "class_tile_map.html", null ],
    [ "TileSet", "class_tile_set.html", null ],
    [ "Timer", "class_timer.html", null ],
    [ "Vec2", "class_vec2.html", null ]
];