/*
 *  File: common.cpp
 *
 *  Description:  Implements common functions
 */

#include <common.hpp>

// Global variable used as debug counter
int debugCount = 0;

// Hotspot screen positions to be used as shortcuts
// The number on the left is x axis and the right one is y axis
pair<float,float> HotspotPos[] = {
	// TOP_LEFT
	{0.0,0.0},
	// TOP
	{0.5,0.0},
	// TOP_RIGHT
	{1.0,0.0},
	// LEFT
	{0.0,0.5},
	// CENTER
	{0.5,0.5},
	// RIGHT
	{1.0,0.5},
	// BOTTOM_LEFT
	{0.0,1.0},
	// BOTTOM
	{0.5,1.0},
	// BOTTOM_RIGHT
	{1.0,1.0}
};

// Returns a color generated by the params
SDL_Color MakeColor(int r,		// red value, 	range: 0 -> 255
										int g,		// green value, range: 0 -> 255
										int b,		// blue value,	range: 0 -> 255
										int a) {	// alpha value, range: unknown
	SDL_Color color;

	color.r = r;
	color.g = g;
	color.b = b;
	color.a = a;

	return color;
}

// Function that compares two float constants
// Returns true if the difference between them is <= than 0.0001 (PRECISION)
bool equals(const float &a, const float &b) {
	return (std::fabs((a-b)) <= PRECISION);
}

// TODO: refactorate for better understanding
// Function that cannot be comprehended by mere human beings
float closeDist(const float &from, const float &to, const float &change) {
	if (abs(from - to) < change) {
		return to;
	}

	if (from > to) {
		return from - change;
	}

	return from + change;
}

// Converts a float number to a string and returns it
string FloatToStr(float f) {
	char s[15];

	sprintf(s,"%.2f",f);

	return s;
}
